# Implicitly requires the IAM_GITHUB_ROLE_ARN secret to be set for the target environment

name: Build image and push to ECR

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: The version to use for the image tag, v2.34.5
      image_name:
        required: true
        type: string
        description: The locally built image name, e.g., eip-ero-applications-api
      ecr_repo:
        required: true
        type: string
        description: The ECR repository name, e.g., applications-api-repo
      preprod_deploy_environment:
        required: true
        type: string
        description: The environment to deploy to, e.g., dev2, int

# Needed for OIDC authentication to AWS
permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    environment: ${{ inputs.preprod_deploy_environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
          cache: gradle

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_GITHUB_ROLE_ARN }}
          role-session-name: ${{ github.run_id }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          AWS_PROFILE_ARG: ""
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ecr_repo }}
          IMAGE_TAG: ${{ inputs.version }}
        run: |
          ./gradlew bootBuildImage
          IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag ${{ inputs.image_name }}:latest $IMAGE
          docker push $IMAGE
