# Implicitly requires the IAM_GITHUB_ROLE_ARN secret to be set for the dev2 environment

name: Build image and deploy to dev2 on merge to main

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
        description: The locally built image name, e.g., eip-ero-applications-api
      ecr_repo:
        required: true
        type: string
        description: The ECR repository name, e.g., applications-api-repo
      app_name_dev2_prefix:
        required: true
        type: string
        description: The app name with the dev2 environment prepended, e.g., dev2-applications-api

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump-semver.outputs.new_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Get latest patch version tag for major version
        id: get-latest-tag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: ${{ github.repository }}
          prefix: 'v2.'

      - name: Bump version tag
        uses: cabinetoffice/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: minor

      - name: Push version tag
        run: |
          tag=${{ steps.bump-semver.outputs.new_version }}
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git tag "${tag}"
          git push origin "${tag}"

  build-and-push:
    needs: tag
    uses: communitiesuk/eip-ero-shared-workflows/.github/workflows/build-and-push.yml@main
    with:
      version: ${{ needs.tag.outputs.version }}
      image_name: ${{ inputs.image_name }}
      ecr_repo: ${{ inputs.ecr_repo }}
      preprod_deploy_environment: dev2

  deploy:
    needs:
      - tag
      - build-and-push
    uses: communitiesuk/eip-ero-shared-workflows/.github/workflows/deploy.yml@main
    with:
      deploy_environment: dev2
      version: ${{ needs.tag.outputs.version }}
      app_name_with_env: ${{ inputs.app_name_dev2_prefix }}
      ecr_repo: ${{ inputs.ecr_repo }}
